"""THE TWO RUFF WAIVERS WIDER THAN AN IGNORE, read across every spelling ruff honours, as a KIT.

WHAT THIS IS FOR. ``exclude`` and ``per-file-ignores`` grant MORE than an ignore does, and every arm
stated over the GLOBAL ignore list is blind to both: an exclude drops every selector over a subtree
and names no code, a per-file ignore drops a named code over a glob. A repo that wants either to
arrive as an edit somebody READ declares its rows as a NAMED SET and calls
:func:`assert_waivers_declared`, which refuses both sides of the ratchet -- an undeclared row, and a
declared row no live config needs.

THE KIT HOLDS NO REPO'S ROWS. Which waivers a repo holds, and why, is a fact about that repo, so it is
declared in that repo's own tests and judged here. This module ships only the reader, the spelling
table and the refusal.

THE AXIS THE READER EXISTS FOR IS SPELLING. Ruff honours ``lint.extend-ignore`` and the DEPRECATED
top-level ``ignore`` as well as ``lint.ignore``, so a reader of the one spelling a repo happens to use
would empty its reading the day an entry moved across spellings while changing nothing ruff does.
:data:`WAIVER_SPELLINGS` is the table that closes it.

PRECEDENCE IS RUFF'S OWN: a ``ruff.toml`` beside a ``pyproject.toml`` WINS -- verified against
``ruff check --show-settings``, which prints the settings path it used -- so a repo carrying both has
one live config and one dead one.
"""

from __future__ import annotations

import tomllib
from collections.abc import Iterable
from pathlib import Path
from typing import Final

from lab_commons.dev.doorcensus import UnreadableRepo, door_text

__all__ = [
    'MACHINE_EXCLUDES',
    'WAIVER_SPELLINGS',
    'UndeclaredWaiverError',
    'WaiverKindError',
    'assert_waivers_declared',
    'ruff_config',
    'ruff_waivers',
    'waiver_drift',
    'waiver_entries',
]

#: EVERY SPELLING RUFF ACCEPTS FOR EACH WAIVER KIND, as a table rather than four `.get` chains.
WAIVER_SPELLINGS: Final[dict[str, tuple[tuple[str, ...], ...]]] = {
    'select': (('lint', 'select'), ('lint', 'extend-select'), ('select',), ('extend-select',)),
    'ignore': (('lint', 'ignore'), ('lint', 'extend-ignore'), ('ignore',), ('extend-ignore',)),
    'exclude': (
        ('exclude',),
        ('extend-exclude',),
        ('lint', 'exclude'),
        ('lint', 'extend-exclude'),
        ('format', 'exclude'),
        ('format', 'extend-exclude'),
    ),
    'per-file-ignores': (
        ('lint', 'per-file-ignores'),
        ('lint', 'extend-per-file-ignores'),
        ('per-file-ignores',),
        ('extend-per-file-ignores',),
    ),
}

#: EXCLUDES THAT HIDE NO SOURCE UNDER REVIEW in any repo: `.git` is git's own store, `.venv*` is
#: installed third-party code, `**/__version__.py` is generated by the version machinery. A caller
#: subtracts them before declaring, so a ceiling counts only excludes that hide REAL source.
MACHINE_EXCLUDES: Final[frozenset[str]] = frozenset({'**/__version__.py', '.git', '.venv*'})


class WaiverKindError(ValueError):
    """A waiver kind the spelling table does not declare. Reading it empty would make a typo look clean."""


class UndeclaredWaiverError(AssertionError):
    """A live waiver no row declares, or a declared row no live config needs -- both NAMED."""


def ruff_config(root: Path, *, at_head: bool) -> dict:
    """Ruff's RESOLVED config for *root*, taking its own precedence rules.

    *at_head* reads the committed config; ``False`` reads the WORKING TREE, which is the right
    answer for the repo under verification (:func:`lab_commons.dev.doorcensus.door_text` argues why).

    Raises:
        UnreadableRepo: there is no ``ruff.toml`` and no ``pyproject.toml`` to read.

    """
    own = door_text(root, 'ruff.toml', at_head=at_head)
    if own is not None:
        return tomllib.loads(own)
    project = door_text(root, 'pyproject.toml', at_head=at_head)
    if project is None:
        msg = f'{root} has no readable pyproject.toml (at_head={at_head}), so its ruff config cannot be read'
        raise UnreadableRepo(msg)
    return tomllib.loads(project).get('tool', {}).get('ruff', {})


def _dig(config: dict, path: tuple[str, ...]) -> object:
    """*config* walked down *path*, or ``None`` the moment a level is missing or is not a table."""
    node: object = config
    for key in path:
        if not isinstance(node, dict):
            return None
        node = node.get(key)
    return node


def waiver_entries(config: dict, kind: str) -> frozenset[str]:
    """Every entry of *kind* in *config*, across ALL of ruff's spellings for it. PURE.

    A ``per-file-ignores`` entry is flattened to ``'<glob>::<code>'`` so both kinds compare as one
    sort of thing -- a set of strings each naming ONE waiver. A glob carrying three codes is three
    rows, so dropping one of them moves the ratchet.

    Raises:
        WaiverKindError: *kind* is not in :data:`WAIVER_SPELLINGS`, or a spelling holds a value that is
            neither a list nor a table.

    """
    if kind not in WAIVER_SPELLINGS:
        msg = f'{kind!r} is not a declared waiver kind; the table names {sorted(WAIVER_SPELLINGS)}'
        raise WaiverKindError(msg)
    out: set[str] = set()
    for path in WAIVER_SPELLINGS[kind]:
        value = _dig(config, path)
        if isinstance(value, dict):
            out |= {f'{glob}::{code}' for glob, codes in value.items() for code in codes}
        elif isinstance(value, list):
            out |= {str(entry) for entry in value}
        elif value is not None:
            msg = f'{".".join(path)} holds a {type(value).__name__}, which is neither a list nor a table of waivers'
            raise WaiverKindError(msg)
    return frozenset(out)


def ruff_waivers(root: Path, kind: str, *, at_head: bool) -> frozenset[str]:
    """Every *kind* entry *root*'s resolved ruff config holds."""
    return waiver_entries(ruff_config(root, at_head=at_head), kind)


def waiver_drift(live: Iterable[str], declared: Iterable[str]) -> tuple[tuple[str, ...], tuple[str, ...]]:
    """``(undeclared, stale)``, both sorted. PURE, so a planted control drives the arithmetic itself."""
    have, said = set(live), set(declared)
    return tuple(sorted(have - said)), tuple(sorted(said - have))


def assert_waivers_declared(
    root: Path,
    kind: str,
    declared: Iterable[str],
    *,
    at_head: bool = False,
    machine: frozenset[str] = frozenset(),
) -> frozenset[str]:
    """Refuse unless *root*'s live *kind* waivers EQUAL *declared*, minus *machine*. Returns the live set.

    Raises:
        UndeclaredWaiverError: a waiver no row declares, or a row no live waiver needs, named.

    """
    live = ruff_waivers(root, kind, at_head=at_head) - machine
    undeclared, stale = waiver_drift(live, declared)
    if undeclared or stale:
        msg = (
            f'{root.name}: ruff `{kind}` holds {list(undeclared)} that no row declares, and the rows declare '
            f'{list(stale)} that no live config needs. An undeclared waiver is invisible to every arm '
            f'stated over the global ignore list; a stale row asserts a constraint on code that no longer '
            f'exists. Declare the first with its reason, delete the second -- never widen the set to quiet it.'
        )
        raise UndeclaredWaiverError(msg)
    return live
