"""THE HOOKS A REPO DECLARES ARE THE HOOKS GIT HAS -- the assertion half, shared.

A ``.pre-commit-config.yaml`` is a DECLARATION; ``pre-commit install`` is a separate act on a separate
machine; nothing links the two. MEASURED 2026-09-16 in three repos at once: each declared a full
configuration and each had ZERO hooks in the directory git actually consults, so every commit through
every one of them had run none of them while the tree read as guarded.

THE MECHANISM WAS ALREADY THE FAMILY'S AND THE TEST BODY WAS NOT. :mod:`lab_commons.dev.hook_install`
has owned resolving the hooks directory THROUGH git, reading the declared set off the configuration,
and telling ``declared-but-absent`` from ``present-but-stale`` from ``present-but-not-pre-commit's``
since 2026-09-16. What stayed forked was the six-arm test that drives it -- three copies, two of them
83% identical in CODE with the difference being exactly a root spelling and a stage set. This module
is that test body, and nothing here re-implements the mechanism: every function below is an
assertion over :func:`lab_commons.dev.hook_install.hook_installation` and its siblings.

THE EXACT-SET PIN IS THE PROPERTY, AND THE DRIFT IT CATCHES ALREADY HAPPENED. The third copy asserts
that the installed stages are a SUPERSET of three names. A superset assertion cannot say WHICH stage
moved: a stage added to the configuration and never installed compares equal, and a stage deleted
leaves a name in the pin that reads as a decision nobody made. So *declared_stages* is compared for
EQUALITY here, both directions red, and the pin is a NAMED SET rather than a count for the reason
this family writes down everywhere else -- an integer cannot name the row that moved, and the
honest-looking repair when it disagrees is to edit the digit.

WHAT ARRIVES WITH NO DEFAULT, and why each is one repo's answer rather than a convenience:

* *root* -- the tree being asked about. A guard rooted at the working directory answers, plausibly,
  about somebody else's checkout.
* *config_name* -- which file holds the declaration. :mod:`lab_commons.dev.hook_install` defaults it
  to pre-commit's own convention, and that default is correct THERE, one layer down, where the
  subject is pre-commit. It is refused HERE because one of the three consumers imports its own
  ``CONFIG_NAME`` from its own module: a consumer that takes the convention writes the constant, one
  visible token, and a consumer that names its file otherwise cannot be silently judged against a
  file it does not have.
* *declared_stages* -- the named set the repo pins. Two consumers differ on it today
  (``{commit-msg, pre-commit}`` against ``{commit-msg, pre-commit, pre-push}``), which is the whole
  reason it cannot be a family constant.

WHAT THIS PROVES, EXACTLY, because overclaiming it would be the defect it guards: a live pre-commit
shim, generated by pre-commit, pointing at THIS configuration, in the matching hook-type slot. It is
strictly weaker than "these hooks pass" and says nothing about whether a hook's own entry resolves.

IT NEVER REPAIRS. A hooks directory is shared by every worktree of a checkout, so an install is a
mutation another party learns about by accident. The remedy is REPORTED and DERIVED --
:func:`lab_commons.dev.hook_install.install_command` builds it from the configuration -- because a
restatement of the stage list is how a stage gets declared and never installed, measured on a fresh
box in 2026-09.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

from lab_commons.dev.hook_install import (
    FOREIGN,
    PROTECTED,
    declared_stages,
    generated_hook,
    hook_installation,
    hooks_dir,
    install_command,
)

__all__ = [
    'assert_a_foreign_hook_is_not_installed',
    'assert_declared_hooks_are_installed',
    'assert_hooks_dir_is_the_one_git_consults',
    'assert_stages_are_declared',
    'assert_the_guard_can_go_both_ways',
    'assert_the_remedy_is_derived',
    'remedy_stages',
]

#: Resolved once: a bare name is a PATH lookup at every call site, and a PATH that answers
#: differently between a terminal and a detached launcher describes an environment nobody meant.
_GIT = shutil.which('git') or 'git'

#: Reading a git path touches no network; a git that has not answered in a minute is hung.
_GIT_TIMEOUT_S = 60


def assert_stages_are_declared(*, root: Path, config_name: str, declared_stages: frozenset[str]) -> None:
    """THE INSTRUMENT'S FLOOR and the two-sided pin, in one arm because they are one question.

    A guard reading an empty declaration is watching nothing, and a guard reading a declaration it
    was not pinned against is watching something else.

    ONE ARM OF THE FORKED COPIES IS NOT HERE, AND ITS ABSENCE IS THE FINDING. All three spelled
    ``assert all(stage.hook_ids for stage in report.stages)`` -- "a stage declaring no hook id is an
    unread configuration". That check CANNOT FAIL:
    :func:`lab_commons.dev.hook_install.declared_stages` groups hook ids BY stage, so a stage exists
    in the report only because an id put it there, and the empty case it guards is unreachable
    through the only path that builds one. The real version of that concern is one layer down and is
    already mechanised -- that parser RAISES on a configuration it could not read rather than
    reporting it empty. A guard no fixture can red is prose with an ``assert`` in front of it.

    Args:
        root: the checkout being asked about.
        config_name: the configuration file that holds the declaration.
        declared_stages: the NAMED SET this repo pins. Compared for equality, both directions.

    Raises:
        AssertionError: when nothing is declared, when the set differs, or when a stage declares no
            hook id -- which is an unread configuration wearing an empty one.

    """
    report = hook_installation(root, config_name=config_name)
    if report.config is None:
        msg = f'no {config_name} at {root}; this guard is watching nothing, so its silence is not a pass'
        raise AssertionError(msg)
    live = {stage.stage for stage in report.stages}
    if live != set(declared_stages):
        msg = (
            f'the declared stages in {report.config} are {sorted(live)}, not {sorted(declared_stages)}. '
            f'Added and not pinned: {sorted(live - set(declared_stages))}; pinned and no longer '
            f'declared: {sorted(set(declared_stages) - live)}. Both directions matter -- a new stage '
            f'must be installed before it counts, and a deleted one must leave this pin in the same '
            f'edit, because a name that outlives its stage reads as a decision nobody made.'
        )
        raise AssertionError(msg)


def assert_declared_hooks_are_installed(*, root: Path, config_name: str) -> None:
    """THE PROPERTY. Green means the commits through this checkout are guarded for real.

    The remedy in the failure message is DERIVED from the configuration, never spelled, so a stage
    added there cannot leave this text telling a reader to install a subset.
    """
    report = hook_installation(root, config_name=config_name)
    if report.verdict == PROTECTED:
        return
    listing = '\n  '.join(f'{stage.stage:<12} {stage.status:<28} {stage.detail}' for stage in report.failing)
    remedy = 'python ' + ' '.join(install_command(root, config_name=config_name))
    msg = (
        f'{len(report.failing)} of {len(report.stages)} declared stage(s) are not live in '
        f'{report.hooks_dir}:\n  {listing}\n\n'
        f'Every commit through this checkout ran none of them, while the tree says they guard it. '
        f'The hooks directory is shared by every worktree on this box, so installing is a deliberate '
        f'act and never a silent repair:\n  {remedy}\n'
    )
    raise AssertionError(msg)


def assert_hooks_dir_is_the_one_git_consults(*, root: Path) -> None:
    """Cross-check the resolved directory against GIT'S OWN answer, never against a rebuilt path.

    A guard that string-built ``.git/hooks`` answers about a directory git may not be using: from a
    worktree there IS no ``<worktree>/.git/hooks``, so it reports every hook absent for the right
    answer by the wrong route, and under a ``core.hooksPath`` redirect it reports every hook absent
    while all of them are present.
    """
    resolved = hooks_dir(root)
    if not resolved.is_dir():
        msg = f'{resolved} is not a directory, so nothing git consults for hooks exists in {root}'
        raise AssertionError(msg)
    named = subprocess.run(
        [_GIT, '-C', str(root), 'rev-parse', '--git-path', 'hooks'],
        capture_output=True,
        text=True,
        check=True,
        timeout=_GIT_TIMEOUT_S,
    ).stdout.strip()
    candidates = {Path(named).resolve(), (root / named).resolve()}
    if resolved.resolve() not in candidates:
        msg = f'{resolved} is not the directory git names ({named}); this guard is inspecting the wrong place'
        raise AssertionError(msg)


def _fixture_checkout(*, root: Path, config_name: str, scratch: Path) -> Path:
    """A REAL repository carrying THIS repository's own configuration, with nothing installed.

    The configuration is COPIED rather than invented, so the control plants what the real reader
    reads: a fixture spelled beside the test drifts from the live configuration silently, and a
    control that has drifted agrees with everything.
    """
    checkout = scratch / 'checkout'
    checkout.mkdir(parents=True, exist_ok=True)
    subprocess.run([_GIT, 'init', '-q', str(checkout)], check=True, capture_output=True, timeout=_GIT_TIMEOUT_S)
    (checkout / config_name).write_text((root / config_name).read_text(encoding='utf-8'), encoding='utf-8')
    return checkout


def assert_the_guard_can_go_both_ways(*, root: Path, config_name: str, scratch: Path) -> None:
    """THE PLANTED CONTROL: absent, then installed, in a real repository, through the real function.

    A guard that is green on the real tree proves nothing by being green -- it could be asserting a
    constant. Both states are planted here and driven through the same function the property uses.
    """
    checkout = _fixture_checkout(root=root, config_name=config_name, scratch=scratch)
    absent = hook_installation(checkout, config_name=config_name)
    if not absent.stages:
        msg = f'the fixture configuration copied from {root / config_name} declares no stage, so this plants nothing'
        raise AssertionError(msg)
    if absent.verdict == PROTECTED:
        msg = f'a freshly initialised repository reported {PROTECTED}; this control cannot fail and proves nothing'
        raise AssertionError(msg)

    directory = hooks_dir(checkout)
    directory.mkdir(parents=True, exist_ok=True)
    for stage in absent.stages:
        (directory / stage.stage).write_text(
            generated_hook(config_name=config_name, hook_type=stage.stage),
            encoding='utf-8',
        )
    installed = hook_installation(checkout, config_name=config_name)
    if installed.verdict != PROTECTED:
        failing = [(stage.stage, stage.status) for stage in installed.failing]
        msg = (
            f"the same repository with pre-commit's own generated shim in every slot still reported "
            f'{installed.verdict} ({failing}); the guard cannot reach its own green, so a red from it '
            f'says nothing about the tree.'
        )
        raise AssertionError(msg)


def assert_a_foreign_hook_is_not_installed(*, root: Path, config_name: str, scratch: Path) -> None:
    """Somebody else's hook is its own finding, because re-installing over one DELETES it.

    THE PLANT IS DERIVED FROM THE CONFIGURATION, never spelled. A fixture that hard-coded one stage
    was measuring one stage and reporting about all of them: the unplanted stage answered
    ``declared-but-absent``, a TRUE finding about the fixture and a false one about the status under
    test. Planting EVERY declared stage is what keeps this arm reading about FOREIGNNESS.
    """
    checkout = _fixture_checkout(root=root, config_name=config_name, scratch=scratch)
    directory = hooks_dir(checkout)
    directory.mkdir(parents=True, exist_ok=True)
    planted = sorted(declared_stages(checkout / config_name))
    if not planted:
        msg = 'the fixture configuration declares no stage, so this plants nothing'
        raise AssertionError(msg)
    for stage in planted:
        (directory / stage).write_text('#!/bin/sh\necho mine\n', encoding='utf-8')
    statuses = {stage.status for stage in hook_installation(checkout, config_name=config_name).stages}
    if statuses != {FOREIGN}:
        msg = (
            f'planting a hand-written hook in every declared slot reported {sorted(statuses)} rather '
            f'than {{{FOREIGN!r}}}. "Somebody else\'s hook" and "pre-commit\'s hook, stale" are two '
            f'findings with two different remedies and may not be collapsed into one.'
        )
        raise AssertionError(msg)


def remedy_stages(*, root: Path, config_name: str) -> frozenset[str]:
    """The stages the derived install command actually names -- PURE, so a consumer can assert on it."""
    command = install_command(root, config_name=config_name)
    return frozenset(command[index + 1] for index, arg in enumerate(command) if arg == '-t')


def assert_the_remedy_is_derived(*, root: Path, config_name: str) -> None:
    """A remedy naming a SUBSET of the declared stages leaves one quietly uninstalled.

    Measured on a fresh box in 2026-09: a hand-written ``Makefile`` target named two of three
    stages, so every hook at the third was declared and never installed while the hooks directory
    looked populated.
    """
    declared = frozenset(declared_stages(root / config_name))
    named = remedy_stages(root=root, config_name=config_name)
    if named != declared:
        msg = (
            f'the install command names {sorted(named)} for a configuration declaring '
            f'{sorted(declared)}; a restated stage list is how a stage gets declared and never installed'
        )
        raise AssertionError(msg)
